### ISSUE TITLE
Knife animation bug 

### ISSUE THREAD

**Issue by nelloiscute** [advancedfx/nSkinz#10]
every other demo is fine but when i try to change skin with having butterfly knife. Knife animations lagging and skipping so hard 

Before change skin : https://streamable.com/poy5zy 

After change skin : https://streamable.com/ujvm2f

**Comment by dtugend** [comment]
Hi, is the issue still present in the [latest version](https://github.com/advancedfx/nSkinz/releases/latest)?
If yes can you provide a demo link and the steps done / stuff replaced (as reduced as possible until the problem happens), please?

**Comment by dtugend** [comment]
Closing in favor of #23
