### ISSUE TITLE
workshop_default paint kits

### ISSUE THREAD

**Issue by lmaeboy** [advancedfx/nSkinz#13]
seems that some csgo update broke this fork some time ago, it is now not possible to change paint kits on anything, the only choice is workshop_default

![Screenshot 2021-05-19 210947](https://user-images.githubusercontent.com/84469414/118862572-8fd4aa00-b8e6-11eb-9fa2-c6706f6be6a4.png)

**Comment by dtugend** [comment]
![image](https://user-images.githubusercontent.com/3610128/119687474-88ae1e80-be47-11eb-999b-5ccb171fb171.png)
I can not reproduce the issue with the last Release ( https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.10 ).

Make sure to load nSkinz before loading the demo, then open the demo (it looks like you are on start screen still) and then check again inisde the demo.

**Comment by dtugend** [comment]
I consider this solved by my reply above until further notice.
