### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by TxnkOwO** [advancedfx/nSkinz#22]
Every time i do the command it doesnt work due to "unknown command"
![image](https://user-images.githubusercontent.com/97200762/148303628-af1b44aa-1cab-4c5d-b637-7b46269a558b.png)

**Comment by xNWP** [comment]
check that hlae has actually loaded by looking in the console after loading csgo. If it hasn't refer to our guide on using hlae with csgo https://github.com/advancedfx/advancedfx/wiki/Your-first-recording-in-CS%3AGO
