### ISSUE TITLE
Knife and gun animation problem

### ISSUE THREAD

**Issue by Siaomo** [advancedfx/nSkinz#23]
I found that the cutting knife will have animation errors, it is strange that the knife will be taken out or swing abnormally, and the AWP will occasionally change bullets by itself
I'm using a translator, sorry, so maybe the text is not very good
I also videotaped the whole process
See if there is a solution
Butterfly knife is more likely to happen, awp will sometimes inexplicably take out and change bullets
https://drive.google.com/file/d/1akCbHXN9MrJflPceMOsn72GLfR3NQMj_/view?usp=sharing

**Comment by dtugend** [comment]
This seems to be related to #10
Can you explain the problem with the AWP with other words, please, I am not sure if I understand the problem with it yet.

**Comment by Siaomo** [comment]
Sorry, I didn't trigger the AWP problem in this video, but the bug with the knife is a bigger problem.
I think the butterfly knife problem is relatively big. Other knives seem to be fine. I am now trying to find a way to see if I can record the bug of AWP.
So can you fix this problem? The butterfly knife problem is very troublesome because I use HLAE to edit the hightlight, but suddenly the video is halfway through and the knife is bugged. It's very uncomfortable.

**Comment by Siaomo** [comment]
I tried my best to find a way to record the AWP problem. I recorded the video to HLAE. I wanted to cut a hightlight, but at the end of the recording, there was a bug in the knife.
Hope you can fix this problem The bug of the sub-cutter of the knife is very strange and this is really annoying, other knives I look good to me I haven't encountered any big problems SKIN some already have an update not bad please Continue to update I think this is used to make hlae HIGHTLIGHT. I really took the SKIN that I don't have and cut it out. It's a bit satisfying for me, please trouble you again

**Comment by dtugend** [comment]
I can't give an ETA on this, since currenty HLAE 3 related things are a priority for me when having time.

However it could be useful to know if the bug happens as well or is less severe, when the original knife model (before you replace it) is the default knife.

**Comment by Siaomo** [comment]
I can understand, after all you have higher priorities
I just reported this kind of problem, and then it seems that I switched to the default knife, and it seems to be normal after repeated tests, the awp bug is that switching the gun to AWP will enter the bullet change action, but I am full of bullets
Another point is that I have the original version of the butterfly knife in my demo. If I change it, there will be bugs in the animation. If I have the preset knife in the game now, it will display normal. I haven't tested it. I will find time to test it. , demo has this knife cutting bug and awp automatically change bullets

**Comment by Siaomo** [comment]
https://drive.google.com/file/d/1Z3ecvl-46bFheF43HkhlhZRK585_S9Et/view?usp=sharing
There is still a problem with watching the DEMO knife, but if you open a custom room and use the default saber, it will be normal

**Comment by dtugend** [comment]
https://github.com/advancedfx/nSkinz/issues/25
> After my test, I found that as long as you use the default saber to hit the BOT, it will be normal, but if you see the demo taking other knives and using nSkinz.dll to switch to your favorite knives or painting, there will be a switching action bug. It's the bug I found now, the video demo can't be used at all, even if I don't add other skins like knives, there will be bugs that I can switch with the knives I own.
> It's a pity, I originally used the original butterfly knife, DEMO wants to change the skin, but there will be a switching action bug, don't use the knife skin, only use the gun skin My original knife will also have animation errors
> If you have time to fix it, after all, you seem to have more important things to deal with~~ I see that other methods of modifying skin are not so easy to use, and a bunch of things need to be installed. This one can be used as long as nSkinz.dll is injected, although it is complicated a little
> GL~~~

**Comment by dtugend** [comment]
I tried to fix it, I hope I didn't break something else in return:
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.14

Due to typos or game updates, there might be combos of original and replacement knife, where the animation is wrong, if so I need to know the exact combo so I can check.

**Comment by dtugend** [comment]
Sorry, last release was bugged, I fixed it:
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.15

**Comment by Siaomo** [comment]
Thank you very much for fixing it. I will find time to test if the DEMO is ok or still have bug. Thank you

**Comment by Siaomo** [comment]
There seems to be no problem with the DEMO cutting knife action problem. It should be able to switch the action normally, but if you open the BOT to play, the knife must choose the preset to avoid the error of switching the knife.
, I only need to change SKIN's weapon to have StatTrak on it, no matter if the weapon is Dragon Lore, it will also have StatTrak, Dragon Lore does not have StatTrak, or I don't want this gun to have StatTrak at all, it will also be forced to display, such as this one
Like this gun Gungnir he doesn't have StatTrak but if I change the SKIN he will force it to attach
![20220213213142_1](https://user-images.githubusercontent.com/78332860/153755576-a55ec604-f793-4002-bd75-db8b85ec733e.jpg)

**Comment by Siaomo** [comment]
Basically, except for this StatTrak problem, I think there should be no problems that need to be fixed, and I will report back if I find problems later.
Thank you for fixing the bug of the DEMO knife switching action, but it has become a mandatory StatTrak no matter what guns will have it

**Comment by dtugend** [comment]
I am not sure if I understood you right, but I assume the issue is that you used a StatTrak skin in the original demo and want to replace it and not have statTrak.
There's an workaround if you are using HLAE anyway, you can remove all StatTrak with mirv_streams:
https://github.com/advancedfx/nSkinz/issues/11#issuecomment-1038130028

**Comment by Siaomo** [comment]
I don't have StatTrak for the original weapon, but using the skin swap will show StatTrak

**Comment by Siaomo** [comment]
mirv_streams add baseFx noStatTrak
mirv_streams edit noStatTrak doBloomAndToneMapping default
mirv_streams edit noStatTrak doDepthOfField default
mirv_streams edit noStatTrak statTrakAction noDraw
mirv_streams preview noStatTrak
May I ask where is this going to be typed or the files in the HLAE folder are deleted?
My English is not very good, I use translation, I can't understand the whole operation

**Comment by dtugend** [comment]
> May I ask where is this going to be typed or the files in the HLAE folder are deleted?

This goes / is enterred into the game's console line by line

**Comment by dtugend** [comment]
> I don't have StatTrak for the original weapon, but using the skin swap will show StatTrak

This would be a bug, I will try if I can reproduce it. Can you screenshot your settings for that weapon (maybe hide the XUID field though if possible).

**Comment by dtugend** [comment]
This is indeed a bug, will try to fix it.

**Comment by Siaomo** [comment]
![螢幕擷取畫面 2022-02-13 223318](https://user-images.githubusercontent.com/78332860/153758334-e9fb6ca9-d78f-48ad-8f44-3b7c79dd30a8.png)
![螢幕擷取畫面 2022-02-13 224102](https://user-images.githubusercontent.com/78332860/153758339-06b60061-ea91-4dde-b0d8-d5dd9e0ba275.png)
The first picture is my equipped weapon, only the pistol has StatTrak
I switched to Gungnir like this DEMO, the offline BOT will be displayed, I did not enter the StatTrak number, it will display itself

**Comment by dtugend** [comment]
Thank you for posting this.
It was my fault, I commented out s.th. when testing earlier and checked it in like that.

advancedfx-v0.1.16 should have that fixed:
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.16

Please note it does however not fix #11 (not being able to hide stattrak), for that use the workaround given earlier.

**Comment by Siaomo** [comment]
Thanks for the fix keep bugging you this fix

**Comment by Siaomo** [comment]
It's normal now, thanks for your fix, I'll report back if I have any problems
should~ maby idk

**Comment by Siaomo** [comment]
I am very worried about whether the knife cutting action bug will appear again. This is very disturbing when it happens during DEMO. It’s okay to play BOT on the computer. It’s annoying to have this kind of screen recording in DEMO.
