### ISSUE TITLE
not working 2022

### ISSUE THREAD

**Issue by Qplik** [advancedfx/nSkinz#24]
i dont know if its just me but this is not working. i use this from " https://csgo-skin-changer.pl/ " and its not working. if its just me/the injector then how can i make this work?

**Comment by sharkzxo** [comment]
same.

**Comment by dtugend** [comment]
Hi sorry for the late reply.

We are **not** related to that website and it seems they are offering an own modified version, which is different from our version. Please understand that this way beyond our scope and we can not help much with that.

The orginal authors provided an contact email on their website:
> Problem z CS GO Skin Changer? Coś nie działa, czegoś brakuje, chciałbyś coś dodać? Skontaktuj się z nami: info@csgo-skin-changer.pl i napisz o czym chcesz! Najlepsze zgłoszenia z chęcią wynagrodzimy, na przykład bezpłatnym skinem!
