### ISSUE TITLE
Possible causes of tool change error

### ISSUE THREAD

**Issue by Siaomo** [advancedfx/nSkinz#25]
After my test, I found that as long as you use the default saber to hit the BOT, it will be normal, but if you see the demo taking other knives and using nSkinz.dll to switch to your favorite knives or painting, there will be a switching action bug. It's the bug I found now, the video demo can't be used at all, even if I don't add other skins like knives, there will be bugs that I can switch with the knives I own.
It's a pity, I originally used the original butterfly knife, DEMO wants to change the skin, but there will be a switching action bug, don't use the knife skin, only use the gun skin My original knife will also have animation errors
If you have time to fix it, after all, you seem to have more important things to deal with~~ I see that other methods of modifying skin are not so easy to use, and a bunch of things need to be installed. This one can be used as long as nSkinz.dll is injected, although it is complicated a little
GL~~~

**Comment by dtugend** [comment]
Closing this in favor of #23

**Comment by dtugend** [comment]
Thanks for the information provided.
I was able to solve some problems, but sometimes the demo doesn't play some animations, I wasn't able to solve that yet, still working on it when having time and motivation.
