### ISSUE TITLE
How to change the key that opens the menu

### ISSUE THREAD

**Issue by malloc2k** [advancedfx/nSkinz#26]
**advancedfx specific?**

No

**Describe the bug**

I wanted to change the key that opens the menu but i cant find a way where do i do it?

**Comment by morganwall** [comment]
Render.cpp line 323:
`if(message_type == WM_KEYUP && w_param == VK_INSERT)`
Change the virtual key to whichever one you want.
You can find a list [here](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes).
