### ISSUE TITLE
使用的详细步骤，我完全不懂程序

### ISSUE THREAD

**Issue by xyzxyzfgdj** [advancedfx/nSkinz#29]

**Comment by Devostated** [comment]
Hello, can you please write in english provide us with informations?

**Comment by xyzxyzfgdj** [comment]
I don't know programming. How to use the skin. Also, can this skin be used in competitive mode and will it be VAC?

**Comment by Devostated** [comment]
Using this doesn't require programming knowledge. This skinchanger is made for using in demos, not in live games.

**Comment by xyzxyzfgdj** [comment]
Have you ever made or know of a skin changer that can be used in live games?

**Comment by Devostated** [comment]
No.

**Comment by dtugend** [comment]
Hi. We are not aware of any skin changers that are allowed to be used with official match making, they all might get you VAC banned eventually when using them, so maybe don't do that.
