### ISSUE TITLE
gloves dont apply correctly

### ISSUE THREAD

**Issue by tanabae** [advancedfx/nSkinz#3]
![Counter-strike  Global Offensive Screenshot 2019 11 16 - 20 00 41 05](https://user-images.githubusercontent.com/57649397/69002873-5021a200-08ac-11ea-859c-396d8dc4db46.png)
this happens when i try using gloves

**Comment by dtugend** [comment]
what's your settings in nSkinz?
did you read readme.txt (the part that says apply, hit update, jump back to round start / demo begin)?

Are you using the latest version ( https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.7 ) hand have read "Known problems" there?

**Comment by dtugend** [comment]
Closing due to lacking feedback.
