### ISSUE TITLE
Bug problem, but it is not clear that it is triggered by the whole

### ISSUE THREAD

**Issue by Siaomo** [advancedfx/nSkinz#30]
I recently started recording the demo again. Other knife switching should be normal. I use Butterfly Knife, Karambit, M9 Bayonet, but the m9 cutting gun bug appeared. I also posted the error of the console. I haven't used the remaining knives, so Not sure if there are more bugs
I am attaching the video
https://drive.google.com/file/d/1xgUOryIzV8bCs_cYymjmNHJ0wq17jN6Q/view?usp=sharing
<img width="293" alt="螢幕擷取畫面 2022-04-30 202009" src="https://user-images.githubusercontent.com/78332860/166105325-9880491e-ab6d-46e0-a338-6c7ec1eb4ced.png">
I found that it seems that it is not my weapon problem, it is that I use other people's weapon SKIN to replace it with the one I want. If I copy his playerInfo.xuid, it seems that there will be a bug. It seems that this is not the knife action broken?! IDK

**Comment by Siaomo** [comment]
Apart from this, I shouldn't have encountered too strange bugs, I will report them immediately~

**Comment by dtugend** [comment]
Hello.

Please first make sure you are really using the latest release:
https://github.com/advancedfx/nSkinz/releases/latest (currently advancedfx-v0.1.16)

The reason is that we fixed quite some knife animation bugs a few releases ago, and the releases look similar, so you might have an outdated one accidentally maybe.

If the bug still persists with the latest release please do the following:
1. Please describe what exactly the bug is (if it's only red warning text appearing in the console, then I'd probably not want to fix that), e.g. if it's a knife animation bug and in which way it can be seen (what is not "normal")? I tried to understand it from the video, but I only noticed the red text to be honest.
2. Please provide a link to / download of the demo in question.
3. Please provide the exact nSkinz.json settings file (often in C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive) e.g. by email to contact@advancedfx.org and please link to this issue, so I know it belongs here.
4. Provide any other information that could be helpful in undersanding the problem.

I tried to get the knife animations right the last updates, but maybe I did some typo or overlooked s.th., so I need you help in understanding the problem.

**Comment by Siaomo** [comment]
Oh sorry English is not my native language so the translation I used may not be very accurate, I now confirm that I am using v0.1.16
Then it should be me using mirv_listentities isPlayer=1
Fetch someone else's "playerInfo.xuid: " and apply it but the teammate's skin doesn't change, this is one of the problems.
Then maybe it's the overpass map CT problem? I'm not sure, there will be a problem with overpass CT switching knives, I don't know why, but I'll report back to you, the video also attaches the test just now, and then I'm continuing to test the map and CT&T problems .
https://drive.google.com/file/d/1P1OjPPHsm-UDwI-Lz8SWXdDUe9ssABZL/view?usp=sharing

**Comment by dtugend** [comment]
I am still not 100% sure I fully understand the problem.
This is a demo. So you need to click update (as you do) and potentially go back to the start of the current round for it to fully update.

**Comment by Siaomo** [comment]
I should have found the problem and click on the CT side. No matter which map is used, switching knives will be a bug, but the T side will not. I just tried Inferno, Mirage, Overpass, and CT will have problems switching knives.
So I guess I see that the DEMO will also have a bug when using the CT side

**Comment by dtugend** [comment]
1. Original
![image](https://user-images.githubusercontent.com/3610128/166108966-ea840144-7b17-4dc9-bd70-69f97a184c75.png)

2. Find XUID of player with `mirv_listentities isPlayer=1` and change to bayonett.
3. Click Update.
4. Go back to round start.

5. Works for me:
![image](https://user-images.githubusercontent.com/3610128/166109026-c7c7dc03-8119-42c7-81b8-e833cafed2f6.png)

**Comment by Siaomo** [comment]
I'm very sorry, I wrongly reported the gun bug, there should be no problem, as long as the round is repeated, the skin will be replaced normally, it should be that I didn't copy the ID to replace the other player's SKIN

**Comment by dtugend** [comment]
No problem.
Does this mean everything is working for you now?

**Comment by Siaomo** [comment]
> 1. Original
>    ![image](https://user-images.githubusercontent.com/3610128/166108966-ea840144-7b17-4dc9-bd70-69f97a184c75.png)
> 2. Find XUID of player with `mirv_listentities isPlayer=1` and change to bayonett.
> 3. Click Update.
> 4. Go back to round start.
> 5. Works for me:
>    ![image](https://user-images.githubusercontent.com/3610128/166109026-c7c7dc03-8119-42c7-81b8-e833cafed2f6.png)

**Comment by Siaomo** [comment]
As long as CT uses the knife of nSkinz-advancedfx-0_1_16, there will be an error in cutting the gun when using it in CT, and if I use other my teammates to replace their knives, there will also be an animation error
I have pressed Click Update and Go back to round start still ct will also be an animation error T-side will not

**Comment by dtugend** [comment]
What exactly is the animation error?
Please try to describe in which way the animation is wrong / what the "cutting gun bug" is?
Does it only happen for certian combinations of knifes (old knife -> new knife)?

(I will try to ask someone from HLAE team to tell me from the video what you mean, because I am not good enough at spotting what's wrong.)

**Comment by Siaomo** [comment]
every time I have a problem with switching knives, I don't open the video, which makes me angry~

**Comment by dtugend** [comment]
A text description would be okay too for me, I just don't understand what to look for.
Chances are we will need a demo and the player and time and settings in question to reproduce the bug on my end and then hopefully be able to fix it.

**Comment by Siaomo** [comment]
This knife animation is wrong. I keep switching guns and this happens. CT is easy to happen, but it has been normal for a while, which makes me very confused. I have never had this problem on the T side.
https://drive.google.com/file/d/1UxDuIwvXjo-M-ejvaF4LYcZ5a1HwgWRE/view?usp=sharing

**Comment by Siaomo** [comment]
At least in this version, my T side has never encountered a video demo with a knife switching error. I just discovered this problem when I recorded a CT demo.

**Comment by dtugend** [comment]
Is the problem, that the switching is not smooth / animating much when they switch between gun and knife?
I am not sure if it's fixable, but I will try to look into it, if you can please send me the demo link / download from the last clip in question.
The problem is the animations on different knifes have different lengths but I am not sure if that's the problem here or s.th. else (e.g. a typo I did on some knife animation properties).

**Comment by Siaomo** [comment]
A while ago, I tested the CT in the CT offline room. Every knife seems to have this problem. I have refreshed and changed the knife every round. I have this problem. If it can't be fixed, I can understand it in Kansai. It takes extra time to debug
I tested it earlier, and the switching animation is even weirder. The knife will shrink. Anyway, it is very weird.... I don't know how to describe the whole thing. Sorry~

**Comment by Siaomo** [comment]
https://drive.google.com/file/d/1y9o9GT-9cODnrYjWS1D07aPrubG1VsO6/view?usp=sharing
Switching to the knife will be like this
AWP 2:17~2:18 Occasionally this will be the AWP empty bomb

**Comment by Siaomo** [comment]
And I also thank you very much for replying to my BUG question, after all, I don't know how to do this kind of program, so I respect and thank you, at least I'm recording DEMO to make myself cool

**Comment by Siaomo** [comment]
Oh, by the way, pressing F to show the knife will also have a problem, his hands will shrink, and occasionally he will auto attack and swing the knife with the left button.

**Comment by dtugend** [comment]
Thanks for the last video, I now understand the problem I think.

Do these problems only happen if the original knife is a Butterfly one?

**Comment by Siaomo** [comment]
I just used DEMO to try other CT players' knives and animation errors
I just cross-tested CT&T and I have taken the original butterfly knife once, and if I change it to another skin, an animation error will occur, so it seems to be the original butterfly knife problem?

**Comment by dtugend** [comment]
Can you check that the nSkinz.dll you load with mirv_loadlibrary is really exactly 578.560 Bytes in file properties, just to make sure you are really on the right dll file?
I will meanwhile try to find a demo with butterfly knife :|

**Comment by Siaomo** [comment]
![image](https://user-images.githubusercontent.com/78332860/166112430-203ab51a-35a5-4557-99e5-50a049528182.png)

**Comment by dtugend** [comment]
Ok, I found a demo and can reproduce the problem, will try to look into it.

**Comment by Siaomo** [comment]
I wish you good luck~ You can take it slow. I'm not in a hurry to use it, but I just happened to demo. I have a butterfly knife and it really gives me a headache, so I have to record the scene without the butterfly knife.

**Comment by dtugend** [comment]
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.17
this should fix it
I had a stupid mistake / typo in code

**Comment by dtugend** [comment]
Thank you for reporting the problem and helping me understand it.

**Comment by Siaomo** [comment]
It seems that there will be such a problem where there is the original butterfly knife. I will attach the video
At 0:51, there is a problem with the quick switch of the knife action, and the M9 is also used.
It may be caused by the fact that I switched weapons too fast, because of the time difference, I only saw your update this morning, I immediately used it in the DEMO test and found that there was a problem, so I ran to the offline mode to test the result.
https://drive.google.com/file/d/1As1nzDVW1Fv0AAanSti8Xg1j1rGr14ri/view?usp=sharing

**Comment by Siaomo** [comment]
If I fire the pill and wait a few seconds before switching the knife, it will be normal, but after shooting with the AWP and switching the knife with Q or 3, the problem will reappear immediately, and the same will happen when the pistol is switched to the knife.
