### ISSUE TITLE
v0.1.17 Bug report

### ISSUE THREAD

**Issue by Siaomo** [advancedfx/nSkinz#31]
It seems that there will be such a problem where there is the original butterfly knife. I will attach the video
At 0:51, there is a problem with the quick switch of the knife action, and the M9 is also used.
It may be caused by the fact that I switched weapons too fast, because of the time difference, I only saw your update this morning, I immediately used it in the DEMO test and found that there was a problem, so I ran to the offline mode to test the result.
https://drive.google.com/file/d/1As1nzDVW1Fv0AAanSti8Xg1j1rGr14ri/view?usp=sharing
If I fire the pill and wait a few seconds before switching the knife, it will be normal, but after shooting with the AWP and switching the knife with Q or 3, the problem will reappear immediately, and the same will happen when the pistol is switched to the knife.
But sometimes when I demo, I will switch weapons very quickly, so this problem is very troublesome

**Comment by dtugend** [comment]
Can you please test this:
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.18

If it doesn't work, I will need a demo, please.

**Comment by Siaomo** [comment]
i will test right now

**Comment by dtugend** [comment]
In case it doesn't work, the demo must be made without nSkinz enabled, so I can test it on my end with enabling it and without, please.

**Comment by Siaomo** [comment]
https://drive.google.com/file/d/1-75c2L0W6bpVl6K0n_cl8rg8bLcSxBhT/view?usp=sharing
It seems that I use the original butterfly knife plus other slin switching animation is normal
But if you replace the knife skin, there will be an animation error. Switching to C4 is also
I'm not sure if this is what you meant to test, I don't understand the translation

**Comment by dtugend** [comment]
I mean:
Do this without nSkinz enabled, please:
1. Join map
2. record demo-name-here
3. mp_restartgame 1
4. do the actions that would trigger the bug a few times.
5. stop (to stop demo recording)
6. zip and upload demo-name-here.dem from your csgo folder.

**Comment by Siaomo** [comment]
understand

**Comment by Siaomo** [comment]
https://drive.google.com/file/d/1jFd3zUWnDkzQHp3a-pJ_5rdl96yaxY2a/view?usp=sharing

**Comment by dtugend** [comment]
Thanks, but I think you forgot mp_restartgame 1 after starting to record, because of this the demo has the ultra low FPS bug
Edit: bascially the demo must contain at least 1 round start, otherwise it will have 1 FPS only.

**Comment by Siaomo** [comment]
oh my bad I re-record

**Comment by Siaomo** [comment]
https://drive.google.com/file/d/1KhZHp_jRKQqZl6x9blJwkYqFb42Dkiso/view?usp=sharing

**Comment by dtugend** [comment]
Thank you very much.

This should fix it
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.19

The remaining problem was that the sequence is set before the weapon index/handle/model switches, so I need to set it again after that.
