### ISSUE TITLE
same problem

### ISSUE THREAD

**Issue by Siaomo** [advancedfx/nSkinz#32]
I have this problem in 04 seconds of the video
DEMO tick time: 103063
I only use Dragon AWP, Claw Knife, Mint Gloves~ You can see the whole problem
If it's not an nSkinz 1.9 problem please let me know, I'm sorry to keep reporting problems
https://drive.google.com/file/d/1bJGI-9scF45G5yOWzn2ivtISE85ZZ6nV/view?usp=sharing, https://drive.google.com/file/d/1nGdHqkVQQ5Ls68u7E7VA5proTwKy8gF8/view?usp=sharing
There will be a situation where the weapon switching action disappears
I'm sorry if the frequent returns are annoying you.

**Comment by Siaomo** [comment]
I found that if you use the knife SKIN +awp skin, there will be the video bug I posted above
But it is normal for me to switch knives with knife SKIN + my original awp skin

**Comment by Siaomo** [comment]
Anyway, DEMO, you can't have AWP skin + knife skin at the same time, one of them will not happen, I don't know why this happens

**Comment by dtugend** [comment]
Is the demo complete and working for you?
It crashes for me if I go forward a two rounds and is "only" 107 MB?
If I do demo_gototick I get the error "Host_Error: CL_CopyExistingEntity: missing client entity 351" and it closes.

**Comment by Siaomo** [comment]
This demo can be played normally, I'm thinking wondering why you crash while watching
As long as I replace the original butterfly knife with other knives, the skin will have problems. If I replace the butterfly knife with sapphire, emerald, and ruby, the display is normal, and the wrong animation in awp can be ruled out. But I have used the original M9 knife to replace the skin without this problem
My original demo is this size
![image](https://user-images.githubusercontent.com/78332860/166176901-bcc91c38-048a-4abc-800c-4826f3aef28b.png)
I just tested using "demo_gototick" to get to that seat, I will be normal I did not use hlae to open, just open csgo to read the demo, it is very strange~~

**Comment by dtugend** [comment]
I redownloaded the demo, strangely enough it works now.

I am assuming you mean the AWP swtich animation skipping in the video at 4 seconds (and it instead wrongly "firing").  
I tried to reproduce the problem, but sadly it just works fine for me.

1. Please take a screenshot of your nSkinz dialogue, so I can see some of the settings and the version at the bottom.

2. Can you send me your C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\nSkinz.json please?  
Otherwise I will at least need the exact order in which you did the settings.

It might also be related to your movie making / recording settings,  
Please make sure to check with the Smoother Demos guide settings correctly applied, so that we are using similar settings:  
https://github.com/advancedfx/advancedfx/wiki/Tutorials#Smoother-demos

**Comment by Siaomo** [comment]
https://drive.google.com/file/d/1Nt_JFqPihz4UKAQXyeBdPMG3XLw3_yhD/view?usp=sharing
I use the original butterfly knife when I use the M9 or claw knife will have a switch gun animation loss, but I use the same butterfly knife skin Gamma Doppler, Doppler will show normal, because afterwards I have cross-testing in the end which is the problem again, so the conclusion down to feel that I use the original butterfly knife set with other knives will happen

**Comment by Siaomo** [comment]
Because I film 34 seconds also happened again a knife action screen disappeared

**Comment by Siaomo** [comment]
![image](https://user-images.githubusercontent.com/78332860/166211648-0d9410b3-bcc4-4700-a501-1a1776f3ae6b.png)

**Comment by Siaomo** [comment]
I only immediately open hlae immediately use nSkinz directly look at the demo did not do other settings on this
csgo I also rechecked the file integrity
The second time I look at the demo, there will be problems

**Comment by Siaomo** [comment]
Round 8, Demo: 98547, I found other demos are also such a problem, so I made a rough inference as follows.
Test1: AWP skin + only use the original butterfly knife (my), the normal animation is no problem
Test2: AWP skin + Lore butterfly knife (replace my original butterfly knife) animation normal no problem
Test3: AWP skin + Emerald Karambit (replaced my original butterfly knife), the seventh second you can see the knife cutting animation error, not normal display out, but directly out of the run
So as long as I take the original butterfly knife may be the opportunity to switch the knife action lost, I used m9 skin to replace other knives should be normal animation, it should be the butterfly knife problem replaced with other types of knives will be so, I also give you the required file, DEMO, nSkinz.json, return to you to see how you correct (I have not used HLAE recording, Just first use nSkinz to watch the DEMO problem)
https://drive.google.com/drive/folders/1YYuzbg_s3oRe34nC8gKEXTF7DGFbTMZa?usp=sharing

**Comment by Siaomo** [comment]
https://drive.google.com/file/d/1O7z6eO4U0Fvt7qgz80ZaL16on3EPT_4C/view?usp=sharing
My AWP is to take Wildfire, name tag: "Dragon Phoenix", the problem came I refreshed the ninth round I bought my own skin will be replaced with Dragon Lore
Then at 55 seconds the blue Dignitas LightXDG took my AWP from previous rounds but did not update to Dragon Lore, other weapons will also have this thing happen, such as a certain orange ID XXX using the original AK, I use mirv_listentities isPlayer=1 to find his playerInfo. xuid: to update his AK weapon skin, there are three AKs on the field, probably none of them will be updated to the skin I replaced.
Have tried to T-side someone's AK replacement, refresh his AK on the field will not be synchronized with the other (I'm not sure if other weapons will also have this problem, may be the same problem I guess)

**Comment by dtugend** [comment]
This should fix both issues:
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.20

**Comment by Siaomo** [comment]
Thanks I will test immediately
