### ISSUE TITLE
Merge more bugs

### ISSUE THREAD

**Issue by Siaomo** [advancedfx/nSkinz#33]
Test 1: switch weapons button 1 ~ 5 will do so, and can not use the F button display, the knife will come out of their own automatic action 6 ~ 10 seconds, and wear is 0.000000 but the weapon display out of the different wear not 0.00000
Test 2: the third person will disappear after the death of the arm which I have found to this problem
Test 3: I changed my own gloves without using other people's weapon skin replacement (weapon synchronization will succeed I have tested but wear 0.000000 but the weapon display out of wear different, not 0.00000 problem is very strange), and then to start their own switch knife action, 22 seconds even A1 guns are gone.Switching weapons so that there is no switching action directly show, the knife will be their own action

Switching to other wear and tear kind of 2.0 more than the casual refresh round instead of Factory New wear and tear is not at all, so I am very confused ~
(A more serious problem than the previous version)
https://drive.google.com/file/d/1B-Wv--UUcFr7uY8-vK5Qk3iK7jkg5k1_/view?usp=sharing, https://drive.google.com/file/d/1Gqen5HKPQ0CgvWccV7V7GalRkunm9ddE/view?usp=sharing, https://drive.google.com/file/d/1Pl5sCcGl5i5ryC6sQUNTFnPRiEyKvjJC/view?usp=sharing

**Comment by dtugend** [comment]
Thanks for your tests.

Please just a really small wear value instead if possible, meaning e.g. 0.00000001 instead of 0, wear 0 means no change for nSkinz, also heigher than 1 is unusual / not normal.

Apart from that this should fix it:
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.22

**Comment by Siaomo** [comment]
I'll report back if have any questions thanks~ Dominik Tugend

Dominik Tugend ***@***.***> 於 2022年5月7日 週六 下午3:21寫道：
