### ISSUE TITLE
report

### ISSUE THREAD

**Issue by Siaomo** [advancedfx/nSkinz#34]
1-1 problem I started to go crazy when I replaced the knife
1-2 I did not replace the knife but normal
2 I don't know, just... It's broken
3 change other DEMO will also have a switch gun problem AWP action does not appear
4 I try to use the video to let you understand what I mean
5 Yu you see, I see already also have a hard to say
https://drive.google.com/drive/folders/1pIIYorpT2uVP6Cedga_G2bKVADcFSEwZ?usp=sharing

**Comment by dtugend** [comment]
Please try: https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.23

Regarding wear:
Please double click on the wear edit field (don't use the slider), then enter a really low value manually like 0.000001 e.g.

**Comment by dtugend** [comment]
There's still another bug, when they switch from bomb to knife in the m9 error demo :(

**Comment by Siaomo** [comment]
I will pay attention to this situation
I am testing, I will reply immediately if I have any questions

**Comment by dtugend** [comment]
Ok I fixed that problem, will upload shortly.

**Comment by Siaomo** [comment]
Oh I'm looking forward to it, I just watched the demo and it looks like everything has been fixed.

**Comment by dtugend** [comment]
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.24
There was a problem, when the model index was switching, but sequence would be same, then it would not update it (you could see it in your m9 error demo on mirage t spawn, the very first one, when switching between knife and bomb).
But it's fixed now.

**Comment by Siaomo** [comment]
thanks ~ Thank you very much for fixing

Dominik Tugend ***@***.***> 於 2022年5月7日 週六 下午5:47寫道：

**Comment by dtugend** [comment]
do you have a twitter, I'd like to tweet about 1.0.24 in case it works for you and would like to mention you (except if you prefer not to)?

**Comment by Siaomo** [comment]
Of course not a problem, after all, is your I am responsible for the return
to let you fix it
https://twitter.com/Siaomo_

Dominik Tugend ***@***.***> 於 2022年5月7日 週六 下午5:54寫道：

**Comment by Siaomo** [comment]
Maybe the translation is a bit strange

Siaomo ***@***.***> 於 2022年5月7日 週六 下午5:57寫道：
