### ISSUE TITLE
How can I update the hud?

### ISSUE THREAD

**Issue by vendami** [advancedfx/nSkinz#35]
For example, I changed my default knife to karambit. The skin itself works, but the hud still shows the default knife. Jumping back one round doesn't really help.

**Comment by dtugend** [comment]
Can you please screenshot your nSkinz settings and upload it here?

Edit: I am specfically interested in the bottom bar of the nSkinz GUI, to see if you ahve the latest version or not.

**Comment by vendami** [comment]
I can just tell the version that I'm using, hold on.

**Comment by vendami** [comment]
I'm pretty sure I'm not using the latest one though, I'll see if it works well with the newest one

**Comment by vendami** [comment]
> I can just tell the version that I'm using, hold on.

Nevermind, I can't! There you go.
![image](https://user-images.githubusercontent.com/49304182/167507054-934961ce-74d0-4e29-a432-19447fc02f65.png)

**Comment by vendami** [comment]
Yup, using the latest version helps. Should've thought of that one first, thanks nonetheless!
