### ISSUE TITLE
Can't open GUI

### ISSUE THREAD

**Issue by Bitlett** [advancedfx/nSkinz#38]
Once injected, pressing Insert doesn't do anything.

It was injected properly, since trying to delete the dll after injecting is not possible due to it being open in csgo.exe

**Comment by dtugend** [comment]
how do you inject it?

When using hlae, it's recommended to load it with `mirv_loadlibrary "C:\...\nSkinz.dll"` command (meaning don't inject it with CustomLoader).

**Comment by dtugend** [comment]
Additionally to above, check that your AntiVirus (e.g. Windows Defender) doesn't interfere with loading it (it did for me when I tested, had to allow it, then it would work, before that mirv_loadlibrary would fail).

**Comment by Bitlett** [comment]
The injector was dogwater. Using a different one fixed the problem.
