### ISSUE TITLE
About VAC

### ISSUE THREAD

**Issue by StavZ** [advancedfx/nSkinz#39]
Is it safe to use only with HLAE tool (in insecure mode) or it's will be bannable too?

**Comment by dtugend** [comment]
If you use HLAE + mirv_loadlibrary command as described in readme.txt to inject nSkinz, then you are safe.

Official HLAE launches CS:GO in insecure mode.

In insecure mode VAC is not active and you can not join VAC protected servers.

Edit:
If you use an own / different injector that allows joining VAC protected servers with the pre-compiled binaries then you might get banned of course.
But as said in `-insecure` mode (the one that makes that popup ingame) you are safe.

**Comment by StavZ** [comment]
One more question, when I close HLAE and run CS:GO from Steam can I play on official servers without vac ban?

**Comment by dtugend** [comment]
Yes HLAE only injects into CS:GO when you launch from HLAE, otherwise it doesn't touch it.

**Comment by StavZ** [comment]
Ok, thank you

**Comment by dtugend** [comment]
If you are new to HLAE and need some help, have a look at https://github.com/advancedfx/advancedfx/wiki/Your-first-recording-in-CS%3AGO and skip the movie recording related parts

**Comment by StavZ** [comment]
Okay, thanks
