### ISSUE TITLE
Imgui issue

### ISSUE THREAD

**Issue by ghost** [advancedfx/nSkinz#40]
cannot open source file "Imgui.h"

how can i fix that

**Comment by dtugend** [comment]
You must clone the repository recursively in order to get the dependencies as well with git or if ithat's too complicated use https://desktop.github.com/

Instructions for git:

```
git clone --recursive https://github.com/advancedfx/nSkinz.git
```

If you already cloned:
```
git submodule update --init --recursive
```

Edit: Fixed URL.
