### ISSUE TITLE
Another butterfly knife error animation occurred again 

### ISSUE THREAD

**Issue by Siaomo** [advancedfx/nSkinz#43]
As always, after the update of nSkinz.dll, the skin knife can not act normally.
https://drive.google.com/file/d/1RDSs9nhxULi83tTmn42edYeEsn_S5f9N/view?usp=sharing, https://drive.google.com/file/d/1UcT4Rsnv1GEWVmrN7YJzWn7WP0fTb5Bt/view?usp=sharing, https://drive.google.com/file/d/1rqj43fILGORH2g-5SuWRPWNMS3dI8rsf/view?usp=sharing

**Comment by dtugend** [comment]
You recorded / tested on an outdated version, the video shows advancedfx-v0.1.24, the current version is advancedfx-v0.1.25.
Also please let us know which is the last version that works for you in case v0.1.25 exposes the same bug.

**Comment by Siaomo** [comment]
Oh, there is a new version of the original is my problem sorry I did not notice 1.24

**Comment by dtugend** [comment]
Please let us know if the new version is good or has the same issue.

**Comment by Siaomo** [comment]
No problem, there are problems will be reported immediately, I did not notice that there is a new version, first dismantled now with all normal
