### ISSUE TITLE
Altering StatTrak weapons makes StatTrak counter print `ERROR! USER UNKNOWN`

### ISSUE THREAD

**Issue by lupusbytes** [advancedfx/nSkinz#44]
When altering a StatTrak weapon, the StatTrak counter prints
`ERROR!` `USER` `UNKNOWN`

---
In the source code, i found
```
static auto apply_config_on_attributable_item(sdk::C_BaseAttributableItem* item, const item_setting* config,
	const unsigned xuid_low) -> void
{
	// Force fallback values to be used.
	item->GetItemIDHigh() = -1;

	// Set the owner of the weapon to our lower XUID. (fixes StatTrak)
	item->GetAccountID() = xuid_low;
...
```
I wonder what the comment means that `item->GetAccountID() = xuid_low;` fixes.

---
I've googled a lot figure out if this unknown user stattrak "bug" is intentional/not adressed, but i haven't been able to find anything on the subject.

**Comment by dtugend** [comment]
Please provide mor details:
- exact nSkins version used (written at the bottom of the GUI of it)
- what your settings are, what means "altering"?
- If you want to remove stattrak see https://github.com/advancedfx/nSkinz/issues/11

**Comment by lupusbytes** [comment]
> Please provide mor details:
> 
>     * exact nSkins version used (written at the bottom of the GUI of it)
nSkinz (advancedfx-v0.1.25)
> 
>     * what your settings are, what means "altering"?
Lets say I want to add a sticker to my ak47 or change the Paint Kit.

![example](https://user-images.githubusercontent.com/18193280/203580393-d13d411d-ef10-4a8c-85b2-a69446a60322.PNG)

In the screenshot, I changed the "Paint Kit" for my real StatTrak Case Hardened to Fire Serpent.
Upon doing so, the StatTrak starts displaying "UNKNWN" and so on, like the weapon is no longer mine, instead of just display the existing kills on it.

--- 
>If you want to remove stattrak see StatTrak change bug #11

I do not wish to remove the StatTrak counter, I want it to carry over to the existing kills, without displaying errors.

**Comment by dtugend** [comment]
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.26
