### ISSUE TITLE
Question on automatic inject on start

### ISSUE THREAD

**Issue by qo** [advancedfx/nSkinz#48]
I'm launching CS:GO via Custom Loader. 

I tried 2 options to inject nSkinz automatically on CS:GO start:
- via DLLs to inject input
- via `+mirv_loadlibrary "Z:\path\to\nSkinz.dll"` in custom launch options

First case nSkinz doesn't display list of Paint Kits.

Second case nSkinz isn't injected at all - LoadLibraryA fails. 

I did some research and probably what stops LoadLibraryA WinAPI function from working is CS:GO not being initialized at the moment of execution of the command. This is also what I consider stopping Paint Kits from being initialized.

I also found that `GetModuleHandleA("serverbrowser.dll")` WinAPI function can tell whether CS:GO has initialized. I consider using it but I might be missing an easier option. Is there?

![nskinz](https://user-images.githubusercontent.com/72982727/218719843-234b6359-5348-4c97-a1fd-4083c271dfe1.png)

**Comment by dtugend** [comment]
This works for me:

1. Remove dll from injector.
2. Create nSkinz.cfg in config folder, contents: `mirv_loadlibrary "C:\\source\\nSkinz\\Release\\nSkinz.dll"`  
(Replace path with your actual path)
2. Use ` +exec nSkinz.cfg` in Launch options.

Pay attention that you need two backslashes instead of one!

**Comment by qo** [comment]
Thanks a lot! Didn't think it would make any difference from a launch option. Turns out cfgs are executed much later than plain launch options :D

**Comment by mrjshzk** [comment]
Hello, sorry for bothering but where should the config folder be located at?

**Comment by qo** [comment]
> Hello, sorry for bothering but where should the config folder be located at?

What's referred by "config folder" is probably your CS:GO config folder. To find it, you should open your Steam, right-click on CS:GO, click "Manage", click "Browse local files". At this point, you should open "csgo" folder and then "cfg" folder. That's where you should create nSkinz.cfg. Hope it helps! :)
