### ISSUE TITLE
How can I add this to my cheat?

### ISSUE THREAD

**Issue by OLD-H28EVR** [advancedfx/nSkinz#49]
I want to add this to my cheat. How do I do I do tha?.

**Comment by Xsintashi** [comment]
Copy files to cheat project and [____](https://learncpp.com)

**Comment by OLD-H28EVR** [comment]
> Copy files to cheat project and [____](https://learncpp.com)

Thanks but can you please tell me what this error is?
[https://imgur.io/a/TXrczm0](https://youtu.be/FKUx9yxMv84)

**Comment by Xsintashi** [comment]
> > Copy files to cheat project and [____](https://learncpp.com)
> 
> Thanks but can you please tell me what this error is? [https://imgur.io/a/TXrczm0](https://youtu.be/FKUx9yxMv84)

Link to another site, that I already know
