### ISSUE TITLE
Missing dll file in .zip

### ISSUE THREAD

**Issue by ZippyLabs** [advancedfx/nSkinz#5]
When I downloaded the .zip it appears the README.txt file but the nSkinz.dll it was not there.

**Comment by dtugend** [comment]
The dll file is inside the download, however your Anti-Virus might delete it thinking it's a Trojan / Virus / ...
We don't have time / motivation to clear nSkinz for AV programs, if in doubt submit a sample of it to your AV provider and ask them to check it.
I can assure you however that we did not intentionally put something awkward inside and it's just compiled from the source code in this repository.
