### ISSUE TITLE
Bug when reloading animations

### ISSUE THREAD

**Issue by mrjshzk** [advancedfx/nSkinz#51]
Normally, when not using this dll and just stock csgo, when you press F to inspect the weapon and R while the inspect animation, it sort of loops again everytime you press again and again. My problem is that when using this dll when I press R during inspect animation it doesnt reload the animation

**Comment by dtugend** [comment]
Please provide:
- a screenshot of your nSkinz settings / dialogue
- a demo on which the problem can be reproduced (edit or alternatively let us know when it only happens outside of demos please)

**Comment by mrjshzk** [comment]
Sure, do you know how can I show the keys I'm pressing while recording? So I can show I'm pressing 'F' and 'R'

**Comment by dtugend** [comment]
Please provide that screenshot first, just in case (I am asking for it, so I can make sure you have the right nSkinz version and not an outdated one).

> Sure, do you know how can I show the keys I'm pressing while recording? So I can show I'm pressing 'F' and 'R'

I don't think I need to know exactly what you pressed when, only need to see the difference when using nSkinz and when not using it, but you can try to enable `demo_recordcommands 1` before recording the demo, then *maybe* I can see them in the demo data (I am not sure though).

Ideally record what you do without nSkinz injected, so we can check the demo both with and without nSkinz properly.

**Comment by mrjshzk** [comment]
Do you think we can arrange a call on Discord so I could screenshare? I feel like that would be easier for both me and you and it should only last a couple minutes.

My discord is hzk#8204

**Comment by dtugend** [comment]
I will try to contact you on Discord, but probably won't manage Thursday (UTC+02:00) anymore.

**Comment by mrjshzk** [comment]
Understandable, contact as soon as you can

**Comment by dtugend** [comment]
(https://youtu.be/ka7eEODKv5k)

**Comment by dtugend** [comment]
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.28
I hope I added no new bugs.

**Comment by mrjshzk** [comment]
> I hope I added no new bugs.

![imagem](https://user-images.githubusercontent.com/115943663/229305838-77028c8f-a752-47b1-b8f8-231972bad7d4.png)

**Comment by dtugend** [comment]
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.30
