### ISSUE TITLE
Skins not showing

### ISSUE THREAD

**Issue by 2cey** [advancedfx/nSkinz#54]
Knife is not showing and is giving the error in console 
Failed to set custom material for 'knife_m9_bay', no matching material name found on model models/weapons/v_knife_default_t.mdl

**Comment by dtugend** [comment]
Please provide more details:
- nSkinz version used (preferably screenshot)
- if it happens in a demo, please provide the demo

**Comment by 2cey** [comment]
> Please provide more details:
> 
> * nSkinz version used (preferably screenshot)
> * if it happens in a demo, please provide the demo
Version: advancedfx-v0.1.30
![image](https://user-images.githubusercontent.com/91031998/229370441-c04fc788-2617-4dba-8141-290a4ecb6e9b.png)
Demo:

**Comment by dtugend** [comment]
I can reproduce the problem on a GOTV demo, thanks.

**Comment by dtugend** [comment]
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.31 should fix the issue.

Don't forget: 

> When you are done setting it up, click update and in demos jump _before_ a round start (or demo begin) and hit play.

https://github.com/advancedfx/nSkinz/blob/advancedfx-v0.1.31/nSkinz-advancedfx-readme.txt#L24
