### ISSUE TITLE
Cannot apply stickers to knife

### ISSUE THREAD

**Issue by Raidtron** [advancedfx/nSkinz#55]
Hello, I'm pretty new to csgo, I wanted to know how I would apply a sticker on a butter knife (Doppler Phase 4 and any sticker in my case)

**Comment by dtugend** [comment]
The game does not support applying stickers to knifes, this is not a bug of nSkinz afaik.

**Comment by Raidtron** [comment]
> 

oh,  i mean i did say im pretty new. Thank you, I'm glad you didn't flame me
