### ISSUE TITLE
Where xuid?

### ISSUE THREAD

**Issue by BxdiS** [advancedfx/nSkinz#57]
![изображение](https://github.com/advancedfx/nSkinz/assets/50522062/9dc5ba33-2179-4726-86ad-6f88d977fdea)
Where is the xuid input field?

**Comment by dtugend** [comment]
We are not related to skinchanger.download, ask that them instead, please.

The downloads for nSkinz advancedfx flavor you can find here: https://github.com/advancedfx/nSkinz/releases

Instructions are here: https://github.com/advancedfx/nSkinz/blob/advancedfx/nSkinz-advancedfx-readme.txt
