### ISSUE TITLE
About hijacking injection

### ISSUE THREAD

**Issue by jackKiZhu** [advancedfx/nSkinz#9]
I would like to ask whether it is effective to implement nskin injection to csgo through hijacking injection?

**Comment by dtugend** [comment]
This is a fork of https://github.com/namazso/nSkinz that is meant for demos and not live usage and as the readme says it can be loaded easily with mirv_loadlibrary console command when using HLAE.

Not sure what you mean by hijacking injection.

**Comment by dtugend** [comment]
Not sure if this answered the question somewhat, if not feel free to comment with further questions.
